version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo "Pre-build phase"
      - dotnet restore
  build:
    commands:
      - dotnet restore
      - dotnet build --configuration Release
  post_build:
    commands:
      - dotnet publish --configuration Release --output artifacts
artifacts:
  files:
    - artifacts/**/*  
  discard-paths: yes
